/**
 * Write DSH credentials + Laguna provider settings from project `.env`.
 * Run: pnpm run setup:credentials
 */
import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { loadProjectEnv, PROJECT_ROOT } from "./load-env.ts";

loadProjectEnv();

const DSH_HOME = process.env.DSH_HOME ?? join(PROJECT_ROOT, "sandbox", ".dsh-home");
const deepseekKey = process.env.DEEPSEEK_API_KEY;
const lagunaKey = process.env.LAGUNA_API_KEY;
const lagunaBaseUrl =
  process.env.LAGUNA_BASE_URL ?? "https://api.commandcode.ai/provider/v1";
const lagunaModel = process.env.LAGUNA_MODEL ?? "poolside/laguna-s-2.1-free";

if (!deepseekKey && !lagunaKey) {
  console.error("Missing keys. Create .env from sandbox/.env.example first.");
  process.exit(1);
}

mkdirSync(DSH_HOME, { recursive: true, mode: 0o700 });

const credentialsLines: string[] = [];
if (deepseekKey) {
  credentialsLines.push(`DEEPSEEK_API_KEY: ${deepseekKey}`);
}
if (lagunaKey) {
  credentialsLines.push(`LAGUNA_API_KEY: ${lagunaKey}`);
}

const credentialsPath = join(DSH_HOME, ".credentials.yaml");
writeFileSync(credentialsPath, `${credentialsLines.join("\n")}\n`, { mode: 0o600 });

const settingsPath = join(DSH_HOME, "settings.yaml");
const settings = [
  "# Generated by pnpm run setup:credentials — edit in DSH Web UI if preferred.",
  "llm-deepseek:",
  "  baseURL: https://api.deepseek.com",
  "  apiKeyEnv: DEEPSEEK_API_KEY",
  ...(lagunaKey
    ? [
        "",
        "llm-pi-ai:",
        "  providers:",
        "    laguna:",
        "      apiKeyEnv: LAGUNA_API_KEY",
        "      api: openai-completions",
        `      baseURL: ${lagunaBaseUrl.replace(/\/$/, "")}`,
        "      compat:",
        "        supportsDeveloperRole: false",
        "        maxTokensField: max_tokens",
        "      models:",
        `        - id: ${lagunaModel}`,
        "          name: Laguna S 2.1 via Command Code",
      ]
    : []),
  "",
].join("\n");
writeFileSync(settingsPath, settings, { mode: 0o600 });

try {
  chmodSync(DSH_HOME, 0o700);
} catch {
  // best effort on platforms without POSIX modes
}

console.log(`DSH_HOME: ${DSH_HOME}`);
console.log(`Wrote: ${credentialsPath}`);
console.log(`Wrote: ${settingsPath}`);
console.log("");
console.log("Next:");
console.log(`  export DSH_HOME="${DSH_HOME}"`);
console.log(`  node node_modules/@deepseek-ai/dsh/lib/bin.js plugin --profile remex-dsh-test add "${PROJECT_ROOT}"`);
console.log(`  node node_modules/@deepseek-ai/dsh/lib/bin.js web`);
